### ISSUE TITLE
[BUG] ERROR  Couldn't add the role (955151821461131386) to the user xxx.

### ISSUE THREAD

**Issue by DeSavanger** [eggsywashere/discord-steam-verification#13]
**I have read all of the README file and checked if this was reported before**
- [x] Yes, I did.
- [ ] No, let me check.

**Describe the bug**
When a user tries to verify themselves in our Discord-server, I'm getting this error:

> ERROR  Couldn't add the role (955151821461131386) to the user xxx.

The role ID is correct and does exist on the server. My bot has every permission and also has the Admin-permission...

**To Reproduce**

- Join my server as a new user
- Getting the message to verify yourself
- Verifying myself with the verify-link I get in PM
- Getting the message ":tada: You have successfully passed verification. Congrats and enjoy our server!"
- Look at the console from nodejs, there you will find the error.

**Expected behavior**
Getting my "**Verified**" role.

**Screenshots**
![image](https://user-images.githubusercontent.com/24686146/165355575-1e872883-8edf-4564-9f7b-b081549b76ed.png)

**System information (required if it's an issue about API or website):**
- OS: Ubuntu 20.04.4 LTS
- Browser: Google Chrome
- Version: latest version of discord-steam-verification
- Node.JS version: v10.19.0

**Additional context**

**Comment by WhiteSasch** [comment]
> Make sure your bot has at least one HIGHER role than the target role.

That indeed was the problem. SOLVED! Thanks man.
