### ISSUE TITLE
how can i run bot from heroku

### ISSUE THREAD

**Issue by serozr** [eggsywashere/discord-steam-verification#14]
I want to run the bot from heroku but I get the error "/bin/sh: 1: tsc: not found heroku"

**Comment by eggsy** [comment]
Sorry, no idea how Node.js works on Heroku, join my Discord and ask there, people might be able to help.

**Comment by eggsy** [comment]
If you're still looking for a hosting service, try out [Hop.io](https://hop.io). It should work just fine! Join their Discord for a private beta key and you'll be good to go. I am closing this issue.
