### ISSUE TITLE
Bug Web

### ISSUE THREAD

**Issue by Hariamane** [eggsywashere/discord-steam-verification#15]
Error: Failed to lookup view "main" in views directory "/root/hariaadminsuite/dist/views"

**Comment by eggsy** [comment]
Hey, do you have a `views` directory in your `dist` folder? And is there a file named `main` in there. If not, maybe you forgot to compile the source and/or script didn't move the `views` directory to build destination. 

Either try to run the _correct_ script (again?) or move the folder manually.

**Comment by Hariamane** [comment]
No I don't have any of these but I can't compile them

**Comment by eggsy** [comment]
Current readme file is outdated, I will update it later, can you try `npm run build`?

**Comment by Hariamane** [comment]
> npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
> npm WARN npm You can find the latest version at https://nodejs.org/
>
> > discord-steam-verification@1.0.2 build /var/www/html/hariaadminsuite
> > rimraf dist && yarn --silent && tsc && rsync --recursive src/views/* dist/views/
>
> sh: 1: rsync: not found
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! discord-steam-verification@1.0.2 build: `rimraf dist && yarn --silent && tsc && rsync --recursive src/views/* dist/views/`
> npm ERR! spawn ENOENT
> npm ERR!
> npm ERR! Failed at the discord-steam-verification@1.0.2 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2022-05-24T21_27_37_730Z-debug.log
> ^C

**Comment by eggsy** [comment]
Seems like you didn't install the modules first, please run `npm install` and wait for the installation and then run `npm run build` again.

**Comment by Hariamane** [comment]
added 46 packages from 56 contributors, removed 32 packages and updated 379 packages in 29.446s
root@themadness /var/www/html/hariaadminsuite # npm run build
npm WARN npm npm does not support Node.js v10.24.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> discord-steam-verification@1.0.2 build /var/www/html/hariaadminsuite
> rimraf dist && yarn --silent && tsc && rsync --recursive src/views/* dist/views/

warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
sh: 1: rsync: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! discord-steam-verification@1.0.2 build: `rimraf dist && yarn --silent && tsc && rsync --recursive src/views/* dist/views/`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the discord-steam-verification@1.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-25T14_40_05_195Z-debug.log

**Comment by eggsy** [comment]
Ugh. Maybe you can just copy all the files inside `src/views` to `dist/views` manually and run `npm run start`.

**Comment by Hariamane** [comment]
Yes I confirm, but I find the system a bit broken

**Comment by eggsy** [comment]
Since I've done many changes in [d2a94f8](https://github.com/eggsy/discord-steam-verification/commit/d2a94f83357224f2b4941a56839fe5d8bc4261d4) and moved to `tsup`, the system should automatically copy the views directory on each successful build. If it fails, there will be an error log stating why it did. The system is much more stable now. It's time to close this issue.
