### ISSUE TITLE
[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by gdavey** [eggsywashere/discord-steam-verification#22]
**Have you checked the features section before making a request?**
- [x] Yes
- [ ] No

**Are you sure if we add this feature, users will be happy about it?**
- [x] Yes
- [ ] No
- [ ] Maybe

**Is this related to a problem, if so, please describe:**
No, it's not.

**Now tell me what's your suggestion**
Would it be possible to add multiple APP_ID i.e our community runs Ark & rust servers so it would be good to check if they have either.

**Comment by eggsy** [comment]
That's a really good idea! I will see what I can do.

**Comment by eggsy** [comment]
There you go! This release includes many optimizations as well as a new UI to for the verification page (see below image).

<img width="600" alt="image" src="https://user-images.githubusercontent.com/13917975/223542311-ae31dbcf-4cd3-42b6-9190-7117c912ede2.png">
