### ISSUE TITLE
[BUG] The requested module 'fs' does not provide an export named 'cp'

### ISSUE THREAD

**Issue by boopxyz** [eggsywashere/discord-steam-verification#24]
Getting this error when building or running dev:

`
import { cp } from "fs";
         ^^
SyntaxError: The requested module 'fs' does not provide an export named 'cp'
`

**Comment by eggsy** [comment]
Hey!

That's weird, I tried building the app on a Windows machine and it worked just fine. Can I see your `node --version`? I think the `cp` method was added in `v16.7.0` to Node.js, so make sure you're using that or a version higher than that one.
