### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by apalesnail** [eggsywashere/discord-steam-verification#27]
Not an issue with the bot!  The bot itself works great.

How would one add an SSL to it?

Thanks

**Comment by eggsy** [comment]
Hi!

If you are hosting your bot on a private server (VPS-), you may need a reverse proxy tool. I am not familiar with them but I've worked with Nginx in the past and getting an SSL certificate for Nginx is really easy with a tool called Certbot. You just install the tool on your server and run the command, it will guide you through the steps and will only ask for some basic information. It supports auto-renewal and so much more, it's really easy to setup if you've come this far.

If you are not using a server that you own, you may need to get in touch with the support team to ask whether it's possible for them to install a SSL certificate for you. I run my bot on Railway which I can reverse proxy to my own domain and handles the SSL for me. You can also try out those services.

**Comment by mosberg12** [comment]
Great! Thanks for the quick response!
