### ISSUE TITLE
[BUG] guildMemberAdd event issues

### ISSUE THREAD

**Issue by OGMatrix** [eggsywashere/discord-steam-verification#4]
**I have read all of the README file and checked if this was reported before**
- [x] Yes, I did.
- [ ] No, let me check.

**Describe the bug**
Bot Guild Member Add Event isnt working.

**To Reproduce**

- Go to `src/events` folder
- Open `guildMemberAdd.js` file
- You'll see that its not working

**Comment by eggsy** [comment]
Any chance you have this option disabled? It's under Discord Developer Dashboard > Your App > Bot

![image](https://user-images.githubusercontent.com/13917975/112164911-55f56900-8bff-11eb-8f10-5581751bab30.jpg)

**Comment by OGMatrix** [comment]
> Any chance you have this option disabled? It's under Discord Developer Dashboard > Your App > Bot
> 
> ![image](https://user-images.githubusercontent.com/13917975/112164911-55f56900-8bff-11eb-8f10-5581751bab30.jpg)

fck this option I hate it
